/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:d3c0d5a1399442bdc9ff95d2d53e82f7:ec169a948eae2079d8ae8be541dc40a7:4c2199d29d449d907da3098a8b2da4c6$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class SpriteSheet
	{
		public const string Blue = "blue";
		public const string Blue_food = "blue_food";
		public const string Blue_gem = "blue_gem";
		public const string Blue_selected = "blue_selected";
		public const string Cyan_food = "cyan_food";
		public const string Cyan_gem = "cyan_gem";
		public const string Empty_cell = "empty_cell";
		public const string Green = "green";
		public const string Green_food = "green_food";
		public const string Green_gem = "green_gem";
		public const string Green_selected = "green_selected";
		public const string Match_three_grid_cell = "match_three_grid_cell";
		public const string Orange_food = "orange_food";
		public const string Pink_food = "pink_food";
		public const string Pink_gem = "pink_gem";
		public const string Purple_food = "purple_food";
		public const string Red = "red";
		public const string Red_foodl = "red_foodl";
		public const string Red_gem = "red_gem";
		public const string Red_selected = "red_selected";
		public const string Snake_grid_cell = "snake_grid_cell";
		public const string Yellow = "yellow";
		public const string Yellow_food = "yellow_food";
		public const string Yellow_gem = "yellow_gem";
		public const string Yellow_selected = "yellow_selected";
	}
}